config/routes.rb
Rails.application.routes.draw do

  root 'products#index'

  resources :products

  post '/products/set_price'

end

app/models/product.rb
class Product < ActiveRecord::Base
	validates_presence_of :name, :original_price
	validates_inclusion_of :price, :in => 1000..10000

	def self.get_suggested_items(original_price, furniture)
		#SQL query that selects 5 products near 60% of original price and of the same furniture type
  	where("furniture_type = ?", "#{furniture}").order("abs(products.price - #{original_price}/0.60)")
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to product_path(@product.id)
    else
      flash[:notice] = "Remember, product must be between $1,000 and $10,000"
      render :new
    end
  end

  def new
    @product = Product.new
    @furniture_types = Product.all.map {|product| product.furniture_type}.uniq
  end

  def set_price
    @product = Product.new(product_params)
    @suggested_items = Product.get_suggested_items(product_params[:original_price], product_params[:furniture_type]).limit(5)
  end

  def show
    @product = Product.find(params[:id])
  end

  def index
    @products = Product.all
  end

  private

  def product_params
    params.require(:product).permit(:name, :price, :original_price, :furniture_type, :suggested_price, :image_url)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Viyet // Sell</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta http-equiv="content-type" content="text/html; charset=UTF-8">
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
		<link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.min.css" rel="stylesheet">
		<!--[if lt IE 9]>
			<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
</head>
<body>
   <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class: "alert alert-info" %>
  <% end %>
  

<header class="navbar navbar-bright navbar-fixed-top" role="banner">
  <div class="container">
    <div class="navbar-header">
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Home", root_path, :class=> "navbar-brand" %>
    </div>
    <nav class="collapse navbar-collapse" role="navigation">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to "List New Product", new_product_path %>
        </li>
      </ul>
    </nav>
  </div>
</header>
<div id="masthead">  
  <div class="container">
    <div class="row">
      <div class="col-md-7">
        <h1>VIYET//sell
          <p class="lead"></p>
        </h1>
      </div>
      <div class="col-md-5">
        <div class="well well-lg"> 
          <div class="row">
            <div class="col-sm-12">
              <a href="https://viyet.com/under-1500.html"><img src= "http://i62.tinypic.com/11lhovq.jpg"></a>
            </div>
          </div>
        </div>
      </div>
    </div> 
  </div><!-- /cont -->
  
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="top-spacer"> </div>
      </div>
    </div> 
  </div><!-- /cont -->
  
</div>

<div class="container">
  <div class="row">
    
    <div class="col-md-12"> 
      
      <div class="panel">
        <div class="panel-body">
          
          <%= yield %>
        
          
        </div>
      </div>
                                                                                       
                                                  
                                                      
    </div><!--/col-12-->
  </div>
</div>
                                                
                                                                                
<hr>

<div class="container" id="footer">
  <div class="row">
    <div class="col">
      
      <h1>Follow Us</h1>
      <div class="btn-group">
       <a class="btn btn-twitter btn-lg" href="http://www.facebook.com/viyetNY"><i class="icon-twitter icon-large"></i> Twitter</a>
     <a class="btn btn-facebook btn-lg" href="https://twitter.com/viyetNY"><i class="icon-facebook icon-large"></i> Facebook</a>
     <a class="btn btn-google-plus btn-lg" href="http://www.pinterest.com/viyet/"><i class="icon-pinterest icon-large"></i> Pinterest</a>

      </div>
      <a href="http://viyet.com"><p class="pull-right">Built for VIYET</p></a>
    </div>
  </div>
</div>

<script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
</body>
</html>

app/views/products/index.html.haml
-@products.each do |product|
	%div.row
		%br
		%div.col-md-2.col-sm-3.text-center
			%img{:src =>"#{product.image_url}", :style => "width:150px;height:150px", :class => "img-rounded"}
		%div.col-md-10.col-sm-9
			%h3 
				#{product.name} 
				%br Now: $#{product.price}
			%div.row
				%div.col-xs-9
					%h4
						%span.label.label-default Was: $#{product.original_price}
					#{product.furniture_type}

app/views/products/new.html.haml
= form_for(@product, url: :products_set_price) do |f|
	= f.label :name, 'Product Name'
	%br 
	= f.text_field :name, :placeholder => "Name the product"
	%br 
	= f.label :original_price, 'Original Price'
	%br 
	= f.text_field :original_price, :placeholder => "Original item price?"
	%br 
	= f.label :image_url, 'Add a photo of your item'
	%br 
	= f.text_field :image_url, :placeholder => "Add Image Url"
	%br 
	= f.label :furniture_type, 'What type of furniture are you selling?'
	%br
	= f.select(:furniture_type, options_for_select(@furniture_types))
	%br
	= f.submit "Next"

app/views/products/set_price.html.haml
%h3 Product Name 
= @product.name
%h3 Original Price
= @product.original_price
%br 

%h3 
= form_for(@product) do |f|
	=f.label :price, "Name your price. (Must be between $1,000 and $10,000)"
	%br 
	=f.text_field :price 
	=f.hidden_field (:name)
	=hidden_field_tag ('name')
	=f.hidden_field (:furniture_type)
	=hidden_field_tag ('furniture_type')
	=f.hidden_field (:original_price)
	=hidden_field_tag ('original_price')


	=f.submit "Next", :class => "btn btn-primary nextBtn btn-lg pull-right"

%h2 -or- 

%h3 Select a suggested price.
%h4 *based on 60% of your products original price
%div.row
	%class.col-md-7
		= form_for(@product) do |f|
			-@suggested_items.each do |item|
				%img{:src =>"#{item.image_url}", :style => "width:150px;height:150px", :class => "img-rounded"}
				%br
				=f.radio_button :price, item.price
				=f.label "#{item.name} - $#{item.price}"
				%br
				=f.label "Original Price:"  " $#{item.original_price}"
				=f.hidden_field (:name)
				=hidden_field_tag ('name')
				=f.hidden_field (:furniture_type)
				=hidden_field_tag ('furniture_type')
				=f.hidden_field (:original_price)
				=hidden_field_tag ('original_price')
				=f.hidden_field (:suggested_price)
				=hidden_field_tag ('suggested_price')
				%br


			=f.submit "Next", :class => "btn btn-primary nextBtn btn-lg pull-right"

app/views/products/show.html.haml
%div.row
	%br
	%div.col-md-2.col-sm-3.text-center
		%img{:src =>"#{@product.image_url}", :style => "width:150px;height:150px", :class => "img-rounded"}
	%div.col-md-10.col-sm-9
		%h3 
			#{@product.name} 
			%br Now: $#{@product.price}
		%div.row
			%div.col-xs-9
				%h4
					%span.label.label-default Was: $#{@product.original_price}
				#{@product.furniture_type}

=link_to 'View All Products on Sale', products_path, :class => "label label-default"
=link_to 'List New Product', root_path, :class => "label label-default"